#!/usr/bin/env bash

if
  [[ -s "/home/l0nglive/.rvm/gems/ruby-2.4.0/environment" ]]
then
  source "/home/l0nglive/.rvm/gems/ruby-2.4.0/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/l0nglive/.rvm/gems/ruby-2.4.0/environment'" >&2
  exit 1
fi
